platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'example' do 
  pod 'AFNetworking', '~> 3'
  pod 'AFOAuthClient', :path => '../'
end
