language: objective-c

xcode_workspace: AFOAuthClient.xcworkspace
xcode_project: AFOAuthClient.xcodeproj
xcode_scheme: AFOAuthClientTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
cache: cocoapods
podfile: Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install

script:
  - set -o pipefail && xcodebuild test -workspace "AFOAuthClient.xcworkspace" -scheme AFOAuthClientTests -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty
  - pod lib lint
